declare const classNames: {
    readonly permalinkInput: 'permalinkInput';
    readonly optionsPage: 'optionsPage';
    readonly plaintextLogicInput: 'plaintextLogicInput';
    readonly permalinkChooser: 'permalinkChooser';
    readonly launchButtons: 'launchButtons';
    readonly continueButton: 'continueButton';
    readonly counters: 'counters';
    readonly optionsTooltip: 'optionsTooltip';
    readonly bold: 'bold';
    readonly optionsCategory: 'optionsCategory';
    readonly optionsTab: 'optionsTab';
    readonly checkboxOption: 'checkboxOption';
    readonly optionsBadRemote: 'optionsBadRemote';
    readonly connectionStatus: 'connectionStatus';
    readonly connectionActions: 'connectionActions';
    readonly connectionToolbar: 'connectionToolbar';
    readonly 'tracker-button': 'tracker-button';
    readonly connectionNote: 'connectionNote';
    readonly loadingState: 'loadingState';
    readonly infoCard: 'infoCard';
};
export = classNames;
